### ISSUE TITLE
hi .thanks  these is the  problem

### ISSUE THREAD

**Issue by valleyss** [notagamedevnono/trinityCore-docker#3]
first, everything is fine,  when it running Processing Map 0  quote :  "[###########################./build.sh: line 169: 29411 Killed                  ${BUILD_FOLDER}/bin/vmap4extractor  ",    what I am gonna do

**Comment by notagamedevnono** [comment]
I can't replicate this error, but the only times I've seen vmap4extractor errors was when I tried to extract maps from an invalid version of the WoW Client. I use the TrueWoW 3.3.5 client, which is pretty widely available. I suggest you ask on the Trinitycore forums, they can help with this, but I'm assuming this error isn't related to this build script.
