### ISSUE TITLE
error docker exec

### ISSUE THREAD

**Issue by ChristophePI6060** [notagamedevnono/trinityCore-docker#5]
Hi

i have an error with this command : 

docker exec -it trinity-db bash -c "mysql -u root -proot  < /var/trinityscripts/create_mysql.sql"
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by notagamedevnono** [comment]
Don't use docker exec, the containers for this project (there are three of them) should be spun up together using docker-compose or some other form of orchestration that binds them. See the included docker-compose file, as well as instructions for how to spin it all up in clean_server.md
